server:
    servlet:
        context-path: /cds-ui
        
spring:
    thymeleaf:
        cache: false
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false