core-ui-app:
    datasource:
        host: localhost
        port: 5432
        name: cds-ui
        username: postgres
        password: postgres

hibernate:
    temp:
        use_jdbc_metadata_defaults: false
        
server:
    servlet:
        context-path: /cds-ui
        
spring:
    thymeleaf:
        cache: false
    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.xml
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://${core-ui-app.datasource.host}:${core-ui-app.datasource.port}/${core-ui-app.datasource.name}
        name:
        username: ${core-ui-app.datasource.username}
        password: ${core-ui-app.datasource.password}
        hikari:
              idle-timeout: 90000
    jpa:
        open-in-view: true
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        database: POSTGRESQL
        show-sql: true
        properties:
            hibernate.format_sql: true
            hibernate.use_sql_comments: true
            hibernate.temp.use_jdbc_metadata_defaults: false        